# docker compose version which is currently 3.8
version: '3.8'

# services : is a list of our container
services:
  # name is optional for our mongodb
  mymongodb:
    image: 'mongo'
    restart: always
    container_name: mongodb
    command: mongod --noauth
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - webappnetwork

  # name is optional for our backend
  backend:
    build: ./
    container_name: aed-map-server
    restart: always
    ports:
      - '3012:3012'

    # depends_on means it will start our backend container once mongo-container is  up and running.
    depends_on:
      - mymongodb
    links:
      - mymongodb
    networks:
      - webappnetwork

  # name is optional for our frontend
  # frontend:
  #   build: ./client
  #   container_name: aed-map-client
  #   restart: always
  #   ports:
  #     - '3000:80'
  #   # it will start our frontend container once backend-container is  up and running.
  #   depends_on:
  #     - backend
  #   links:
  #     - backend
  #   networks:
  #     - webappnetwork

networks:
  webappnetwork:
    driver: bridge

# declare the volumes name that our app is using.
volumes:
  data:
