version: 2.1

jobs:
  build_node_server:
    working_directory: ~/build
    docker:
      - image: cimg/base:2022.06
    steps:
      - run:
          name: Create eu-central-1-key.pem file from circleci envs and add full permissions to it
          command: |
            echo "${AWS_3040_KEY_CONTENT}" >> eu-central-1-key.pem
            sudo chmod -R 777 eu-central-1-key.pem
      - run:
          name: Connect to EC2 instance
          command: |
            ssh -i "eu-central-1-key.pem" ubuntu@ec2-18-196-174-22.eu-central-1.compute.amazonaws.com -y
      - run:
          name: Go to app folder, switch to develop branch and pull changes
          command: |
            cd app/AED-Map/
            git switch develop
            git pull
      - run:
          name: Reinstall node_modules
          command: |
            rm -rf node_modules/
            yarn install
      - run:
          name: Restart node server via pm2
          command: |
            pm2 stop all
            pm2 delete all
            pm2 start npm --name="AED-MAP-NODE" -- run "start:server:dev"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_node_server:
          filters:
            branches:
              only:
                - master
                - develop
