export const SET_MAP_ZOOM = 'SET_MAP_ZOOM';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_TRANSPORT_TYPE = 'SET_TRANSPORT_TYPE';
export const SET_ROUTE_END_POSITION =
  'SET_ROUTE_END_POSITION';
export const SET_NEAREST_DEF_INDEX =
  'SET_NEAREST_DEF_INDEX';
export const INCREMENT_NEAREST_DEF_INDEX =
  'INCREMENT_NEAREST_DEF_INDEX';
export const IS_SEARCH_NEXT_NEAREST_DEF_BUTTON =
  'IS_SEARCH_NEXT_NEAREST_DEF_BUTTON';
