export const SET_USER_POSITION = 'SET_USER_POSITION';
export const INPUT_USER_POSITION = 'INPUT_USER_POSITION';
export const INPUT_USER_POSITION_PLACEHOLDER = 'INPUT_USER_POSITION_PLACEHOLDER';
export const SET_GEOLOCATION_STATUS =
  'SET_GEOLOCATION_STATUS';

export const START_WATCHING_POSITION =
  'START_WATCHING_POSITION';
export const STOP_WATCHING_POSITION =
  'STOP_WATCHING_POSITION';
